USE [master]
GO
/****** Object:  Database [WeatherForecast]    Script Date: 05/09/2025 13:40:02 ******/
CREATE DATABASE [WeatherForecast]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WeatherForecast', FILENAME = N'D:\Databases\SQL Server\MSSQL16.LocalDb\WeatherForecast.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WeatherForecast_log', FILENAME = N'D:\Databases\SQL Server\MSSQL16.LocalDb\WeatherForecast_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [WeatherForecast] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WeatherForecast].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WeatherForecast] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WeatherForecast] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WeatherForecast] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WeatherForecast] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WeatherForecast] SET ARITHABORT OFF 
GO
ALTER DATABASE [WeatherForecast] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WeatherForecast] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WeatherForecast] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WeatherForecast] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WeatherForecast] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WeatherForecast] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WeatherForecast] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WeatherForecast] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WeatherForecast] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WeatherForecast] SET  DISABLE_BROKER 
GO
ALTER DATABASE [WeatherForecast] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WeatherForecast] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WeatherForecast] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WeatherForecast] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WeatherForecast] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WeatherForecast] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WeatherForecast] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WeatherForecast] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WeatherForecast] SET  MULTI_USER 
GO
ALTER DATABASE [WeatherForecast] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WeatherForecast] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WeatherForecast] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WeatherForecast] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WeatherForecast] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [WeatherForecast] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [WeatherForecast] SET QUERY_STORE = ON
GO
ALTER DATABASE [WeatherForecast] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [WeatherForecast]
GO
/****** Object:  UserDefinedTableType [dbo].[Forecasts]    Script Date: 05/09/2025 13:40:02 ******/
CREATE TYPE [dbo].[Forecasts] AS TABLE(
	[Date] [date] NOT NULL,
	[TemperatureC] [int] NOT NULL,
	[Summary] [nvarchar](255) NOT NULL
)
GO
/****** Object:  Table [dbo].[RegionForecasts]    Script Date: 05/09/2025 13:40:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegionForecasts](
	[RegionId] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[TemperatureC] [int] NOT NULL,
	[Summary] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_RegionForecasts] PRIMARY KEY NONCLUSTERED 
(
	[RegionId] ASC,
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Regions]    Script Date: 05/09/2025 13:40:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Regions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_Regions] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Regions_Name]    Script Date: 05/09/2025 13:40:03 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Regions_Name] ON [dbo].[Regions]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RegionForecasts]  WITH NOCHECK ADD  CONSTRAINT [FK_Forecasts_Regions] FOREIGN KEY([RegionId])
REFERENCES [dbo].[Regions] ([Id])
GO
ALTER TABLE [dbo].[RegionForecasts] CHECK CONSTRAINT [FK_Forecasts_Regions]
GO
/****** Object:  StoredProcedure [dbo].[CreateForecasts]    Script Date: 05/09/2025 13:40:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CreateForecasts]
(
	@RegionId int,
	@Forecasts Forecasts READONLY
) AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO RegionForecasts
	SELECT 
		@RegionId, 
		[Date], 
		TemperatureC,
		Summary 
	FROM @Forecasts
END
GO
/****** Object:  StoredProcedure [dbo].[ReadForecasts]    Script Date: 05/09/2025 13:40:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ReadForecasts]
(
	@RegionId int
) AS
BEGIN
SELECT 
	[Date],
	TemperatureC,
	Summary
  FROM RegionForecasts
  WHERE @RegionId = @RegionId AND [Date] > GETDATE()
END
GO
USE [master]
GO
ALTER DATABASE [WeatherForecast] SET  READ_WRITE 
GO
